name: Phobia CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run bench verify
      run: make -C bench verify

    - name: Set up arm-none-eabi-gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: latest

    - name: Build REV5A firmware
      run: make -C src HWREV=REV5A

    - name: Build PESC1 firmware
      run: make -C src HWREV=PESC1

    - name: Build VESC6A firmware
      run: make -C src HWREV=VESC6A

