name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run bench verify
      run: make -C bench verify

    - name: Set up arm-none-eabi-gcc
      uses: ryanwinter/arm-none-eabi-gcc@master
      with:
        release: '10.3-2021.10'

    - name: Build REV5A firmware
      run: make -C src HWREV=REV5A

    - name: Build PESC1 firmware
      run: make -C src HWREV=PESC1

    - name: Build VESC6A firmware
      run: make -C src HWREV=VESC6A

    - name: Set up libsdl-org
      uses: libsdl-org/setup-sdl@main
      id: sdl
      with:
        install-linux-dependencies: true
        version: 2-latest
        version-sdl-image: 2-latest
        version-sdl-ttf: 2-latest

    - name: Build GUI front-end software
      run: make -C phobia

