name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Run bench test
      run: make -C bench test

    - name: Set up arm-none-eabi-gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: latest

    - name: Build REV5A firmware
      run: make -C src HWREV=PHOBIA_rev5

    - name: Build PESC1 firmware
      run: make -C src HWREV=PESC_r1

    - name: Build FSESC67 firmware
      run: make -C src HWREV=MKESC_60100_v2

